### PR TITLE
Add dashboard to statistics page

### LINKED ISSUE #794: Add dashboard to satistics
Currently, when a stacker visits `satistics` they see a table of all their stacking and spending.

Ideally we'd also give them a graphical view of their personal activity like on our [analytics page](https://stacker.news/stackers/month) (which only applies to everyone).

We have a couple views that periodically refresh and have all the data needed: `user_stats_(day|week|month)` and has these columns:

```
t TIMESTAMP(3), id INTEGER, comments BIGINT, posts BIGINT, territories BIGINT,
    referrals BIGINT, msats_tipped BIGINT, msats_rewards BIGINT, msats_referrals BIGINT,
    msats_revenue BIGINT, msats_stacked BIGINT, msats_fees BIGINT, msats_donated BIGINT,
    msats_billing BIGINT, msats_spent BIGINT
```

### PR DESCRIPTION
**Pull request by dillon-co**
closes #794

Moved `pages/statistics.js` to a directory with 2 files for routing and tabbing between the 2 files `pages/statistics/history.js` and `pages/statistics/graphs/[when].js`

That's where the conflicting file message is coming from

Screenshot from 2024-03-28 15-20-37
Screenshot from 2024-03-28 15-37-26

Fixed all these issues @kr pointed out in the last PR.

- [x] tab between table and graphs 
- [x] fix x-axis (times)
- [x] msats -> sats
- [x] labels
- [x] fix text wrap
- [x] mobile UI/UX
- [x] allow selecting time periods

## Summary by CodeRabbit

- **New Features**
	- Introduced new queries for fetching user statistics over time, including actions, incoming, and outgoing transactions.
	- Added a new page for visualizing user statistics with dynamic charts, improving data analysis and user engagement.
	- Updated navigation to include a more detailed statistics history, enhancing user experience with direct access to specific data insights.

- **Enhancements**
	- Modified navigation links in the user dropdown and usage header for better clarity and accessibility to statistics and history.

- **Bug Fixes**
	- Corrected navigation paths in the statistics section to ensure accurate data fetching and display.

### CODE REVIEW

**Review by huumn — CHANGES_REQUESTED** [review]
This still has a last mile or so to go on details. Finding and enumerating the details will take me about as much time as time as fixing them myself.

If you'd like to do the work yourself, I'm happy to enumerate them. Otherwise, I can take it the last mile.

Let me know.

**Comment by dillon-co** [comment]
If it could be one cycle I'll do it but if you think it'll be more then you can take it lol. I'd do it just to get a better feel for how to do the UI for these issues but I also want to work on other issues too

**Comment by huumn** [comment]
It'll probably be a handful of cycles. There's a bunch of tinsy UI things that are only exposed with lots of manual testing. I'll try to finish it up soon. It's really cool and I'm sure a lot of people will love having it.

**Comment by huumn** [comment]
This was taken the last mile in #1099.

Where should I send your sats @dillon-co

**Comment by dillon-co** [comment]
@huumn Just DM'd you on slack

**Pull request closed without merging**
