### PR TITLE
add shellcheck workflow

### LINKED ISSUE #1143: Add github action to shellcheck sndev
Use https://github.com/marketplace/actions/shellcheck to check `/sndev` ... we want it to be posix compliant.

### PR DESCRIPTION
**Pull request by hkarani**
## Description
closes #1143

## Checklist

**Are your changes backwards compatible? Please answer below:**

**Did you QA this? Could we deploy this straight to production? Please answer below:**

**For frontend changes: Tested on mobile? Please answer below:**

**Did you introduce any new environment variables? If so, call them out explicitly here:**

### CODE REVIEW

**Comment by benalleng** [comment]
Nice!
got a question about how we can fix the shellcheck failures
```
./sndev:42:16: note: Double quote to prevent globbing and word splitting. [SC2086]
./sndev:53:16: note: Double quote to prevent globbing and word splitting. [SC2086]
./sndev:64:16: note: Double quote to prevent globbing and word splitting. [SC2086]
```
for these three they are all pointing to this repeated code block
```
  t=$1
  if [ "$t" = "-t" ]; then
    shift
  else
    t=""
  fi
``` 
but i can't immediately see where there isn't a double quote

**Comment by hkarani** [comment]
Yeah I also got caught by this when I tried to do a test fix. Can ./sndev pass all the tests after the fixes?

**Comment by benalleng** [comment]
Go ahead and push up the changes recommended by the tests and we'll see!

**Comment by huumn** [comment]
I think we want to ignore shellcheck warnings, ie this workflow should only "fail" when shellcheck reports an error. 

Some of the warnings are not real issues and fixing them leads to problems.

**Comment by hkarani** [comment]
Shellcheck now fails with error severites

**Comment by huumn** [comment]
@hkarani do you have a lightning address I can send the award to?

**Comment by hkarani** [comment]
lnbc200u1pnyf7kjpp57lwjtgud6qaruwpa82zp83uply2rtdtacgee5pkch8cjadd8kvfsdpcge6kuerfdenjqsrpwd6x2unfwd4nxv3qdahzqum5v93kketj9ehx2amncqzzsxqrrsssp5uevwget85sjmw9s5p93394luu79sdj540shsvt8xvqu0a59nh2pq9qyyssqpakdznxs9undftme227q2g89cvmp2lv908r96saeg8yggh9wq5p9u08u4nuful83gasmjnjrell7hxwjf9fjlaagfwraukzhr9v9jcsq4s67d8

**Comment by hkarani** [comment]
@huumn my stackernews username https://stacker.news/asterisk32

lnbc200u1pnyfl8zpp5qfxqg3fy7e9t087eh94qgz4qpzh97djdpkvmdkryd80tfrrmkhwqdpcge6kuerfdenjqsrpwd6x2unfwd4nxv3qdahzqum5v93kketj9ehx2amncqzzsxqrrsssp5vk25dhfj30scv60vuqtp8cusdpl0gl4lr6hjlm5aj22vm9rs3njs9qyyssq4yg27eutep99qdmnzx9kvtftw5qk6ehm94pal2th22qvk6vzvk75zt898fmc4exttr5pvhh99pfjmlhu8epg3vqadzptk9stdqmseuqpykm88q

**Pull request merged**
