### PR TITLE
move search bar to top of page

### PR DESCRIPTION
**Pull request by rleed**
The approach is straightforward: put the search controls at the top of the results list, similarly to the illustrations in the mockups of issue #365. If the user scrolls, the search bar assumes a floating position at the top of the screen and the list of items scrolls underneath it (as also suggested in the mockups).

Representative screenshots non-scrolled and scrolled:

Untitled

Notes on the CSS changes:
- the searchSection and searchPadding classes are sort of complementary (only one is display: block at a time)
- they both have an associated class "float" that toggles on and off depending on scroll position
- a media query was needed to fill in missing container padding on xs screens (not sure why it was missing). I would have preferred an @include directive not to hard-code the bootstrap xs width in the @media query, but that is only possible in scss files, not modules, and I didn't think it would be good to risk global scss changes just for this unique case.
- the form left/right were set to 0 because the containers already provide the correct (responsive) shape.
- the form flex-flow was set to nowrap to fix unsightly overlaps of the search inputs with other parts of the page on very narrow window sizes.

### CODE REVIEW

**Comment by huumn** [comment]
I'd like the selects to be moved below the dropdown. Do you want to take a stab at that or should I?

**Comment by huumn** [comment]
Yes below the search box please!

**Comment by rleed** [comment]
Untitled

Besides moving the inputs, I also moved the `my-3` class from one div to the other to keep the spacing equivalent.

**Comment by huumn** [comment]
Looks great!

**Comment by ekzyis** [comment]
This branch also got messed up somehow. Maybe a rebase will help?

**Comment by huumn** [comment]
I have rebased thee

**Comment by rleed** [comment]
Sorry about the merge mess... I think I've got the hang of it now after fixing the other one.

**Pull request merged**
