### PR TITLE
Item popover

### PR DESCRIPTION
**Pull request by felipebueno**
## Description

Just like the User Popover but for items. The motivation was the same, to have a little bit more information about an item without having to navigate to the item.

More info here: https://stacker.news/items/530617

## Screenshots

image

image

## Checklist

**Are your changes backwards compatible? Please answer below:**

Yes

**Did you QA this? Could we deploy this straight to production? Please answer below:**

Not yet

**For frontend changes: Tested on mobile? Please answer below:**

It's a desktop only feature

**Did you introduce any new environment variables? If so, call them out explicitly here:**

No

## TODO

- [x] Introduce HoverablePopover and refactor UserPopover and ItemPopover to use it

### CODE REVIEW

**Review by huumn — CHANGES_REQUESTED** [review]
At a glance, the code looks directionally right!

From QA:

1. if the `item` is a comment, this just displays `ItemInfo` which is weird
    - this makes me curious how this handles `#<item number>/related` and other such links
2. there's excess bottom padding on the `ItemPopover`
    - this was also true in the user popover PR but I ended up fixing it

**Comment by felipebueno** [comment]
> 1. if the item is a comment, this just displays ItemInfo which is weird

Oh, I forgot to test it with comment links

>   this makes me curious how this handles #<item number>/related and other such links

Good question

I'll test it and work on the fixes today

**Comment by felipebueno** [comment]
> 1. if the `item` is a comment, this just displays `ItemInfo` which is weird

What do you think of these solutions:

Max two lines for the title/text on ItemSummary
image

Fix paddings
image

For when there's no title:
image
image

**Comment by felipebueno** [comment]
> this makes me curious how this handles #<item number>/related and other such links

Can you give me examples of such links? I tried ```#<item number>/related``` but it throws 404

**Comment by huumn** [comment]
> @huumn what do you think of these solutions?

Looks great. If it's not a huge lift, can we make the comment look more like a comment? e.g. `ItemInfo` on top and text not bold?

> Can you give me examples of such links? I tried #<item number>/related but it throws 404

This is the type of link: https://stacker.news/items/538496/related
It's rendered like: [#538496/related](https://stacker.news/items/538496/related)

**Comment by felipebueno** [comment]
> If it's not a huge lift, can we make the comment look more like a comment?

Sure can, no problem :)

> This is the type of link: https://stacker.news/items/538496/related

Hmm for some reason, those related links are not working in development. It probably has something to do with the related posts not being loaded... the skeleton never finishes loading 

image

image

image

**Comment by huumn** [comment]
fyi related requires the search engine to run

**Comment by felipebueno** [comment]
> fyi related requires the search engine to run

oops... thanks

> If it's not a huge lift, can we make the comment look more like a comment? e.g. ItemInfo on top and text not bold?

You mean something like this?

Comment Item:
image

Normal Item:
image

**Comment by huumn** [comment]
Yep!

**Comment by felipebueno** [comment]
@huumn done!

```/related``` item links:
image

Comment item links:
image

Normal item links:
image

**Comment by huumn** [comment]
Well done!

**Pull request merged**
