### PR TITLE
sndev cleanup

### LINKED ISSUE #1533: Refactor sndev to have fewer commands
sndev is beginning to get kludgy with overexposed, poor UX commands.

After #1521 gets merged, I'd like to reduce the surface area of sndev to:

```bash
[keyan stackernews]🍏 sndev   

                            888
                            888
                            888
      .d8888b  88888b.  .d88888  .d88b.  888  888
     88K      888 '88b d88' 888 d8P  Y8b 888  888
     'Y8888b. 888  888 888  888 88888888 Y88  88P
          X88 888  888 Y88b 888 Y8b.      Y8bd8P
      88888P' 888  888  'Y88888  'Y8888    Y88P

manages a docker based stacker news development environment

USAGE
  $ sndev [COMMAND]
  $ sndev help [COMMAND]

COMMANDS
  help                    show help

  env:
    start                 start env
    stop                  stop env
    restart               restart env
    status                status of env
    logs                  logs from env
    delete                delete env

  sn:
    login                 login as a nym
    set_balance    set account balance of nym

  lightning:
    fund                   pay a bolt11 for funding
    withdraw               create a bolt11 for withdrawal

  db:
    psql                   open psql on db
    prisma                 run prisma commands

  dev:
    pr                     fetch and checkout a pr
    lint                   run linters

  other:
    cli                    passthrough to service cli
    open                   open GUI in browser
    onion                  get the onion address of a container
    cert                   get the tls cert of a container
    compose                docker compose passthrough
```

For things like onion/cert/cli, we'll want to define the paths/commands as container labels like we do with the `CONNECT` label. Then the interface for them would probably work like `sndev onion SERVICE`.

For fund/withdraw, we'll want a flag for using `cln` instead of the default, `lnd`.

### PR DESCRIPTION
**Pull request by huumn**
closes #1533

You'll have to delete and restart containers after this is merged. It renames `stacker_(lnd|cln)` to `(lnd|cln)` and relies on docker compose labels to provide access to service clis/onions/certs now.

This replaces:

- `sndev fund_user` -> `sndev set_balance`
- `sndev (stacker|sn)_(lndcli|clncli|litcli)` -> `sndev cli (lnd|sn_lnd|cln|litd)`
- `sndev (stacker_(lnd|cln)|lnbits) get_onion` -> `sndev onion (lnd|cln|lnbits)`
- `sndev stacker_lnd get_cert` -> `sndev cert lnd`
- `sndev (fund|withdraw)_cln` -> `sndev (fund|withdraw) --cln`

This adds:

- `sndev test` command (which just runs our one jest test)

### CODE REVIEW

**Comment by riccardobl** [comment]
This is unrelated to the pr, but i've noticed  that some sndev commands do not work in my ubuntu workstation if i run it with `./sndev`. The cause seems to be the use of bash conditional expressions `[[ ]]` that are not supported by the real `/bin/sh` (even though /bin/sh might be a symlink to /bin/bash in some distro).

Imo for correctness we should use the shebang  `#!/bin/bash`

**Comment by huumn** [comment]
That's weird because is passed the shellcheck check job we run on prs.

**Comment by huumn** [comment]
Ah it's not catching that problem because it's just a warning. I'll fix that in this pr. I think I added a few more of those bash syntax conditionals.

**Comment by huumn** [comment]
Should be fixed. There was just one usages of `[[ COND ]]` in `fund_user` (now `set_balance`).

**Pull request merged**
