### PR TITLE
Support other currencies

### LINKED ISSUE #103: Add other currencies for displaying bitcoin price

### PR DESCRIPTION
**Pull request by ekzyis**
Hey! Thanks for your website, I have really fallen in love with it and visit it every day!

But I missed a user setting to choose the preferred currency, so I added it; open source ftw! :smile: (closes #103)

I have only added `EUR`, but other currencies which coinbase supports are easy to add. Just add it together with the symbol to `CURRENCY_SYMBOLS` in `components/price.js`.

At first, I wanted to use a dropdown to choose the currency in the settings, but I didn't found a dropdown I could reuse, so I just went with a text input first.

Please tell me if you like it and if I should adapt anything :+1:

### CODE REVIEW

**Comment by ekzyis** [comment]
Some impressions:

2022-09-13-021754_1920x1080_scrot

2022-09-13-021810_1920x1080_scrot

2022-09-13-021841_1920x1080_scrot

**Comment by huumn** [comment]
Overall looks pretty good. I'm pretty swamped with stuff but I'll try to take a closer look soon.

I agree a dropdown would be a much better UX.

**Comment by ekzyis** [comment]
I implemented it as a dropdown now. Also added currencies suggested by a user here: https://stacker.news/items/69184

Also fixed some errors if the user is not logged in yet and thus `fiatCurrency` does not exist on the `me` object in https://github.com/stackernews/stacker.news/pull/192/commits/22e07a4318b2637db0e948a433b58b68633120f5

2022-09-18-035437_1920x1080_scrot

**Comment by huumn** [comment]
Nice job! I'll try to merge this soon

**Comment by ekzyis** [comment]
I see there are conflicts and the dropdown has the same issue as described in #200. 

Will resolve conflicts and check dropdown scrollbars soon.

**Comment by huumn** [comment]
My bad. Merged out of order. 

I plan to merge this PR and the other remaining tomorrow. I can fix myself if you don't have time.

**Comment by ekzyis** [comment]
> My bad. Merged out of order.
> 
> I plan to merge this PR and the other remaining tomorrow. I can fix myself if you don't have time.

Haha, I actually like resolving conflicts. I used the Github GUI now. It is actually decent for small conflicts like these.

I didn't check #200 however. Not sure if that needs a separate fix here or will be automatically fixed because it uses the same CSS (most likely)

**Pull request merged**
