### PR TITLE
remove leaky text in uploadMarker

### LINKED ISSUE #1096: Image alt attributes leak data
**Is your feature request related to a problem? Please describe.**

When users upload an image, we use the provided filename in the markdown image syntax for the image alt attribute. We use it as a marker so we know which text we can replace when upload is finished:

https://github.com/stackernews/stacker.news/blob/d7ecbbae3a86ac62d3ad30f5affa8d240c722ce0/components/form.js#L316-L343

However, this can leak information like when the image was taken as in this example:

``

**Describe the solution you'd like**

Overwrite filename with random string or simply delete string for the image alt attribute. 

**Describe alternatives you've considered**

n/a

**Additional context**

When to overwrite filenames or delete them is not clear. If we do this on upload, then the user might be confused which image was uploaded since the filename no longer matches what they uploaded. The code also needs unique identifiers so simply deleting it on upload would break the `onSuccess` callback. We could do this after `onSuccess` though.

We could do this on submit on the client or server but then we need to parse for image alt attributes and then it's not clear which was provided by the user and which should be replaced. We could limit this replacement to images from `m.stacker.news` though.

[_sats for this ticket go to @Darth-Coin even though he probably does not want them_](https://stacker.news/items/512387)

### PR DESCRIPTION
**Pull request by itsrealfake**
## Description

closes #1096

## Checklist

**Are your changes backwards compatible? Please answer below:**

**Did you QA this? Could we deploy this straight to production? Please answer below:**

**For frontend changes: Tested on mobile? Please answer below:**

**Did you introduce any new environment variables? If so, call them out explicitly here:**

### CODE REVIEW

**Review by ekzyis — APPROVED** [review]
Works great!

**Comment by itsrealfake** [comment]
> Works great!

Swag. How does this get merged?

**Comment by huumn** [comment]
I merge it when I'm in a reviewing/merging/award data entry mood.

**Comment by itsrealfake** [comment]
while writing a comment which took advantage of this, i had a thought about a feature

when the user uploads their first image, a UX like 

### 1. Logged  user uploads from clipboard w/ e.g. CMD+V


### 2. Popup to save preference option

> "we automatically strip EXIF data in the upload process. 
> what would you like stacker.news to do when you upload images?
>   - do nothing
>   - show you an option dialogue to create a link to source
> (you can change this later in preferences)

### 3. Show a dialogue to optionally leave a link to source w/ pasted image.

> Would you like to add a link to the image source?
> You can change this option in user preferences.

**Comment by ekzyis** [comment]
What do you mean with "link" here?

> would you like stacker.news to leave a link when paste images into a comment box?

**Pull request merged**
