### PR TITLE
Format internal links as #<id>

### PR DESCRIPTION
**Pull request by ekzyis**
This formats links like https://stacker.news/items/395051 to [#395051](https://stacker.news/items/395051)

### CODE REVIEW

**Comment by huumn** [comment]
Excited about this one. I've been think a lot about https://github.com/stackernews/stacker.news/issues/350 lately. 

For this change, I think we'll want to handle two other cases:

1. referral links, because many folks use the `copy link` action
2. comment links using `copy link` which I changed here https://github.com/stackernews/stacker.news/commit/d14123cc4258bda726e279ffb67c3c0dc04c2932

So we'll want a regex that matches something that looks like this: `https://stacker.news/items/<item id>[/r/<nym>][?commentId=<item id>]`

**Comment by ekzyis** [comment]
With cad1258, this:

```
https://stacker.news/items/395051

https://stacker.news/items/395051

https://stacker.news/items/395051foobar

https://stacker.news/items/395051/r/ekzyis

https://stacker.news/items/328193/r/ekzyis?commentId=395064

https://stacker.news/items/328193?commentId=395064&parentId=1241
```

gets formatted to:

```
[#395051](https://stacker.news/items/395051)

[#395051](https://stacker.news/items/395051)

https://stacker.news/items/395051foobar

[#395051](https://stacker.news/items/395051/r/ekzyis)

[#328193](https://stacker.news/items/328193/r/ekzyis?commentId=395064)

[#328193](https://stacker.news/items/328193?commentId=395064&parentId=1241)
```

See https://regexr.com/7qola

**Comment by huumn** [comment]
Not a huge deal but shouldn't this `[#328193](https://stacker.news/items/328193/r/ekzyis?commentId=395064)` show the `commentId`, ie `[#395064](https://stacker.news/items/328193/r/ekzyis?commentId=395064)`, given that's what that links to?

**Comment by ekzyis** [comment]
> Not a huge deal but shouldn't this `[#328193](https://stacker.news/items/328193/r/ekzyis?commentId=395064)` show the `commentId`, ie `[#395064](https://stacker.news/items/328193/r/ekzyis?commentId=395064)`, given that's what that links to?

Ah good point, I agree

**Comment by ekzyis** [comment]
Done in [3873cbb](https://github.com/stackernews/stacker.news/pull/765/commits/3873cbb2934095cc5ce887d547a3f9ce9fa5bffb). 

Also refactored the code. I realized we can leverage URL parsing using the `URL` constrcutor. need for a complicated regexp. Now the code doesn't even need to care about the origin.

**Comment by huumn** [comment]
This change turns `[this in my text for the url](https://stacker.news/items/328193)` by turning it into `[#328193](https://stacker.news/items/328193)` which is not what you want. I think you just need to move the code block for this change to later in the function.

**Comment by ekzyis** [comment]
> This change turns `[this in my text for the url](https://stacker.news/items/328193)` into `[#328193](https://stacker.news/items/328193)` which is probably not what you want. I think you just need to move the code block for this change to later in the function.

Good catch, fixed in [c34c2a4](https://github.com/stackernews/stacker.news/pull/765/commits/c34c2a4db4473a02c27ee2992a7c13ad4ee0e22c)

**Pull request merged**
