### PR TITLE
Fix '{' expected

### PR DESCRIPTION
**Pull request by ekzyis**

### CODE REVIEW

**Comment by huumn** [comment]
Is this just a style consistency change?

**Comment by ekzyis** [comment]
Yes, kind of. The code still compiles but vscode marked this as an error:

2022-09-20-004351_1920x1080_scrot

**Comment by huumn** [comment]
I don't get this error. I wonder why.

**Comment by ekzyis** [comment]
Maybe you have `javascript.validate.enable` set to false somewhere in your vscode settings: https://stackoverflow.com/a/52568994/13555687

See screenshots:
2022-09-20-135922_1920x1080_scrot
_`javascript.validate.enable` set to true -> errors shows_

2022-09-20-135916_1920x1080_scrot
_`javascript.validate.enable` set to false -> no error shown (it's still red however)_

**Comment by huumn** [comment]
That's probably it

**Pull request merged**
