### PR TITLE
Frontend payment UX cleanup

### PR DESCRIPTION
**Pull request by ekzyis**
## Description

This includes all frontend changes from #1184 (especially the changes from https://github.com/stackernews/stacker.news/pull/1071) and supersedes it.

https://github.com/stackernews/stacker.news/issues/849 is not closed by this but this closes https://github.com/stackernews/stacker.news/issues/848

## Additional Context

See https://github.com/stackernews/stacker.news/pull/1184#issuecomment-2132916938

## Checklist

**Are your changes backwards compatible? Please answer below:**

Yes

**Did you QA this? Could we deploy this straight to production? Please answer below:**

Yes

**For frontend changes: Tested on mobile? Please answer below:**

**Did you introduce any new environment variables? If so, call them out explicitly here:**

### CODE REVIEW

**Comment by huumn** [comment]
I think this is the right move. The systemic fix is a pretty dramatic change. I'll QA and hopefully merge this today. 

How this'll go:
1. merge this
2. implement systemic overhaul (I have a local design that's nearly flushed out)
3. build not-custodial zaps #1178 into the systemic overhaul

**Comment by huumn** [comment]
QA went pretty well until I did a bunch of zaps and the invoices started expiring.

For every expired invoice (about 10-15 of them), this modal popped up, one after the other on an unrelated page:

Screenshot 2024-05-27 at 12 30 10 PM

I'll do a line by line now, but QA is good other than the above.

**Comment by huumn** [comment]
Nothing else came up in QA and line by line looks fine. Let me know if you want to fix the above issue before merging.

**Review by huumn — APPROVED** [review]
Good to merge but one bug.

**Comment by huumn** [comment]
I did the same thing and the QR didn't show.

However, now I have payments failing that don't appear in my notifications:

Screenshot 2024-05-28 at 12 14 25 PM

Screenshot 2024-05-28 at 12 16 59 PM

I suspect not all the invoices are being recorded. Anyway, I'm going to merge as it's probably something easy for you to fix when you're back online.

**Comment by ekzyis** [comment]
Good catch! When there are multiple errors which will show an modal, new modals replace the previous ones since `showModal` encloses the same values in each payment "thread". The call of one `showModal` in one thread does not update `showModal` in the other threads so they overwrite each other instead of stacking. The state is already "locked in".

I'm trying to get around this with `useRef` to have mutable state across components.

**Pull request merged**
