### PR TITLE
Add a date selector to the search function

### PR DESCRIPTION
**Pull request by rleed**
I'm opening this in draft state (pertaining to issue #410) because I've gotten stuck and I want to ask if someone has insight on what I'm missing.

I've added the date picker to the UI in this PR, and it works fine up to and including updating the `values` object and the query parameters in the location bar. However, when clicking the search button to actually perform the search, the `values` revert back to what seem to be the initial values, and I do not understand why or where those are coming from.

Does anyone have insight on why that is happening?

### CODE REVIEW

**Comment by huumn** [comment]
It's because the search button trigger `onSubmit` which calls `search` with the `Form` values. You are storing your date range in the search component's state and the values sent for `onSubmit` come from the `Form`'s state. 

Make sense?

**Comment by rleed** [comment]
Yeah, that makes sense. I was thinking `formik.values` took care of it, but now I see I need to use `helpers.setValue` as well.

**Comment by huumn** [comment]
The code for this looks simple and good but the UI is too bad on mobile to ship. 

Going to drop in draft until you or I can fix that.

**Comment by rleed** [comment]
Updated to wrap the date selector on mobile.

image

**Pull request merged**
