### PR TITLE
fix: adjusts the navbar and signup button for mobile

### PR DESCRIPTION
**Pull request by cyphercosmo**
_Updated on `Fri Dec 20 23:09:21 2024 UTC`_

## Description

A simple change to address issue #1648 by removing a conflicting tailwind class and only passing it when it's necessary.

## Screenshots

image

## Checklist

**Are your changes backwards compatible? Please answer below:**
Yes

**On a scale of 1-10 how well and how have you QA'd this change and any features it might affect? Please answer below:**
10

**For frontend changes: Tested on mobile, light and dark mode? Please answer below:**
Yes

**Did you introduce any new environment variables? If so, call them out explicitly here:**
No

### CODE REVIEW

**Comment by huumn** [comment]
Awesome, but I'd rather make the button the right size. The effect of your change is to obstruct more pixels of what people want to see.

**Review by huumn — CHANGES_REQUESTED** [review]
As I said in my other comment please

**Comment by cyphercosmo** [comment]
I agree @huumn, on it.

**Comment by cyphercosmo** [comment]
Please check @huumn , I found the best solution to be a mix of making the nav bar slightly bigger but also reducing the size of the button.

Any suggestions?

**Review by huumn — CHANGES_REQUESTED** [review]
My suggestion is the same. We do not want the navbar larger. Just make the button smaller please.

**Comment by cyphercosmo** [comment]
If I only make the button small it continues to touch the navbar edge as when you reported, I'm trying to not introduce custom CSS only for this button but rather I'm using the CSS framework you guys chose.

If you have something specific in mind how it should look please share, otherwise I prefer to not continue trying to guess exactly what I should do that will look decent.

**Comment by ekzyis** [comment]
I think all this needs is to remove the vertical padding. This stops the button from touching the top and bottom:

https://github.com/user-attachments/assets/8f221d19-7738-4175-a002-86e9fa4d5b12

I also tried to apply some vertical margin but that makes the navbar height increase instead of decreasing the height of the button.

**Comment by cyphercosmo** [comment]
Okay, I tried your approach @ekzyis, I noticed that the SignupButton had this `py-1` class hardcoded so I checked the references to this component and the only place except the sticky bar it's currently being used is when you click the anon icon, so I made the change to pass it explicitly in that case, checked it for both situations and it's working.

**Review by cyphercosmo — COMMENTED** [review]
The reason I'm saying I removed a conflicting class is because the `className` variable defaults to `py-0` and no use of the component was passing the class name.

**Comment by huumn** [comment]
Do you have a lightning address @cyphercosmo? I owe you some sats for this

**Comment by cyphercosmo** [comment]
Hey @huumn ! 

Yes it's cyphercosmo@getalby.com.

Looking forward to contributing more, also feel free to ask if there is something important you need done.

**Pull request merged**
