### PR TITLE
Add search hints to initial search page

### PR DESCRIPTION
**Pull request by rleed**
This is to address issue #274.

Untitled

(The ~sub syntax didn't seem to work for me...note to self to check into it.)

### CODE REVIEW

**Comment by rleed** [comment]
> (The ~sub syntax didn't seem to work for me...note to self to check into it.)

Following up on this, there seems to be a disconnect in `resolvers/search.js`. I added the changes to this PR that I think are needed, but I could not find a way to test the fix. Is there a way to test the search function (OpenSearch) on a local dev setup? (...I need to be able to test it for another PR too.)

**Comment by huumn** [comment]
> (The ~sub syntax didn't seem to work for me...note to self to check into it.)

I think I broke support for this at some point and you search within a sub by going to `/~sub/search`

>  Is there a way to test the search function (OpenSearch) on a local dev setup?

If you're using docker we'd have to add another container to the cluster. This is something I'd like to add so happy to sponsor you doing that if you want.

**Comment by rleed** [comment]
> If you're using docker we'd have to add another container to the cluster. This is something I'd like to add so happy to sponsor you doing that if you want.

Great, yeah, I'm using docker (on Windoze). I'm happy to take that on!

**Comment by rleed** [comment]
Revision to the hint:

Untitled

**Comment by huumn** [comment]
Looks great! Nice work!

**Pull request merged**
