### PR TITLE
Add comment scrolling in capture

### LINKED ISSUE #977: Have 'capture' service scroll to comment for comment links
Comment links are of the form: https://stacker.news/items/481416/r/k00b?commentId=481643

But, our capture service does not wait for us to scroll to `commentId` before screenshotting. This should make it do that.

### PR DESCRIPTION
**Pull request by benalleng**
## Description

Adds comment scrolling in the capture worker

Closes #977 

## Screenshots

image

## Additional Context

doesn't work with outlawed comments, only tested since this was top today https://stacker.news/items/508204 
perhaps a `?outlaw=true` query param is in order in the future?

## Checklist

- [x] Are your changes backwards compatible?

- [x] Did you QA this? Could we deploy this straight to production?

## Summary by CodeRabbit

- **New Features**
	- Enhanced the screenshot tool to automatically scroll to and capture a specific comment when provided with a comment ID in the URL.

### CODE REVIEW

**Comment by benalleng** [comment]
This only works because of a rave condition, I made a mistake assuming that the comment had an id and I just spent a bunch of time staring at it 😅

**Comment by huumn** [comment]
We use the ref like this to scroll to it:

```jsx
  useEffect(() => {
    setCollapse(window.localStorage.getItem(`commentCollapse:${item.id}`) || collapse)
    if (Number(router.query.commentId) === Number(item.id)) {
      // HACK wait for other comments to collapse if they're collapsed
      setTimeout(() => {
        ref.current.scrollIntoView({ behavior: 'instant', block: 'start' })
        ref.current.classList.add('outline-it')
      }, 100)
    }
  }, [item.id, router.query.commentId])
```

If you wait 200ms after loading (or something like it), it should scroll.

**Comment by benalleng** [comment]
Since we add this `ref.current.classList.add('outline-it')` after we scroll down to the comment i decided to use the `.waitForSelector()` method provided by puppeteer to wait on so that the class must be added and it must be in view to proceed

**Comment by huumn** [comment]
Brilliant!

**Comment by huumn** [comment]
This isn't working in prod. It might need a delay or something. https://capture.stacker.news/items/509319/r/k00b?commentId=509326.

**Comment by benalleng** [comment]
Dang it! Ok I can add a 200ms delay to see if it waits for the scroll more consistently

**Pull request merged**
