### PR TITLE
Add thread subscriptions

### LINKED ISSUE #283: Add ability to subscribe to threads
moneyball asked about this recently ... its something I've been wanting to do but was going to do it with an overlapping feature.

Basically: user who isn't OP can get notifications about new comments to an item.

It's pretty straightforward.

### PR DESCRIPTION
**Pull request by ekzyis**
Closes #283 

https://github.com/stackernews/stacker.news/assets/27162016/20ae2fbe-41a2-47a9-823b-a1621e4e6977

### CODE REVIEW

**Comment by ekzyis** [comment]
I think the code can also be used to implement "muting" of threads.
Sometimes, people start to argue under a comment of oneself and one doesn't want to follow the discussion but you can't disable notifications for this specific thread.

I think that adding a column `ThreadSubscription.mute` and updating the `WHERE` parts like this would be enough:
```diff
- WHERE (p."userId" = $1 OR p.id = ANY(SELECT "itemId" FROM "ThreadSubscription" WHERE "userId" = $1))
+ WHERE (p."userId" = $1 OR p.id = ANY(SELECT "itemId" FROM "ThreadSubscription" WHERE "userId" = $1 AND mute = false))
+ AND NOT p.id = ANY(SELECT "itemId" FROM "ThreadSubscription" WHERE "userId" = $1 AND mute = true))
 AND "Item".created_at > $2::timestamp(3) without time zone
```

**Comment by huumn** [comment]
I shouldn't have force rebased that. My bad. My PR flow is WIP obviously

**Comment by huumn** [comment]
> I think the code can also be used to implement "muting" of threads. Sometimes, people start to argue under a comment of oneself and one doesn't want to follow the discussion but you can't disable notifications for this specific thread.
> 
> I think that adding a column `ThreadSubscription.mute` and updating the `WHERE` parts like this would be enough:
> 
> ```diff
> - WHERE (p."userId" = $1 OR p.id = ANY(SELECT "itemId" FROM "ThreadSubscription" WHERE "userId" = $1))
> + WHERE (p."userId" = $1 OR p.id = ANY(SELECT "itemId" FROM "ThreadSubscription" WHERE "userId" = $1 AND mute = false))
> + AND NOT p.id = ANY(SELECT "itemId" FROM "ThreadSubscription" WHERE "userId" = $1 AND mute = true))
>  AND "Item".created_at > $2::timestamp(3) without time zone
> ```

That'd work but this query was slow for me - query planner was iterating over all parent/child pairs (>>100k rows) then checking it against the few thread subscriptions ... often taking ~30 seconds. 

If users want to mute their items, it's probably best to put it in the "Item" model as a boolean.

**Comment by huumn** [comment]
Nice work. Going to merge but please review the changes I made to get a feel for what was missing.

**Comment by ekzyis** [comment]
> please review the changes I made to get a feel for what was missing.

Changes make sense! I'll mark my PRs as drafts in the future when I don't think it's ready to get merged yet.
For example, with this one, I only wanted to get early feedback and didn't mean to propose to merge this as-is before further testing like how the query plan actually looks :smile:

**Comment by huumn** [comment]
> > please review the changes I made to get a feel for what was missing.
> 
> Changes make sense! I'll mark my PRs as drafts in the future when I don't think it's ready to get merged yet. For example, with this one, I only wanted to get early feedback and didn't mean to propose to merge this as-is before further testing like how the query plan actually looks 😄

All good. The query plans change depending on the size of tables, historical access patterns, write patterns, memory available, etc. It'll be hard for you test query plans without prod scale data. I occasionally dump the prod DB to test with locally. I'll try to generate you a scrubbed prod dump soon that you can use for developing.

**Pull request merged**
