### PR TITLE
Notifications with nostr info

### LINKED ISSUE #337: Show zap message
**Is your feature request related to a problem? Please describe.**

People can attach messages to zaps on nostr. If people use their SN address as the Lightning address, they can't see that message.

**Describe the solution you'd like**

See zap message in notifications

**Describe alternatives you've considered**

Complaining on SN lol

**Additional context**

https://stacker.news/items/192759

### LINKED ISSUE #364: Show user/pubkey of nostr originating zaps in notifications
Request from Super. Wants to see who is zapping him on nostr without having to go to nostr.

### PR DESCRIPTION
**Pull request by ekzyis**
Closes #337, closes #364

_notifications now show zap messages and shortened pubkey:_
2023-07-28-062528_922x435_scrot

_full nostr zap request event available in invoice view:_ 
2023-07-28-062214_1920x1080_scrot

Since #337 was requested by @nerd2ninja, I am pinging you here for feedback :)

Regarding #364, it only shows the pubkey for now ... will look up how to fetch user names from nostr

TODO:
- [ ] fetch user name from nostr and show in nostr message (?)

### CODE REVIEW

**Comment by nerd2ninja** [comment]
Has this been pushed to mainnet yet? I tried zapping my own note on nostr and my message didn't show on SN.

**Comment by ekzyis** [comment]
Noo, this is just a pull request. Not merged to master and deployed yet. Just wanted to ask what you think about the screenshots. Anything that is missing in your opinion?

**Comment by nerd2ninja** [comment]
Ah yes it looks good. Usernames (petnames) are NIP-02 https://github.com/nostr-protocol/nips/blob/master/02.md 

The nostr client can show us what note was actually zapped, so I think its okay to leave that out (until someone else requests it XD)

**Comment by ekzyis** [comment]
Mhh, I think we could fetch the user names in the next iteration on this feature.

It's not clear to me where this should be fetched: client-side or server-side and if server-side, every time notifications are fetched (imo bad) or once during payment in `/lnurlp/[username]/pay.js`?

However, afaict, SN does not connect to any nostr relay anywhere yet so I would have installed `nostr-tools` for that since that's also what is used in OS (outer.space). But I think this will require too much of my time now and I would rather start working on #354 and #366. So I will undraft this PR as it is

**Comment by huumn** [comment]
> However, afaict, SN does not connect to any nostr relay anywhere yet 

We do. It's only when receiving zaps. worker/nostr.js

**Comment by huumn** [comment]
I wonder if we should do all this extra nostr work there ... Store the note as jsonb in a column in the invoice table and grab zapping user metadata.

**Comment by ekzyis** [comment]
> We do. It's only when receiving zaps. worker/nostr.js

Ahh, that's where I've seen the code using `Relay(r)`. I was searching for `new Relay` but didn't find it.
And makes sense, we need to send zap receipts for NIP-57

**Pull request merged**
