### PR TITLE
refactor: Check darkmode in useWallets

### PR DESCRIPTION
**Pull request by ekzyis**
## Description

`useWallets` is a more appropriate location to check which image we should use.

## Checklist

**Are your changes backwards compatible? Please answer below:**

yes

**On a scale of 1-10 how well and how have you QA'd this change and any features it might affect? Please answer below:**

`8`. The correct image is still used in light and dark mode.

**For frontend changes: Tested on mobile, light and dark mode? Please answer below:**

**Did you introduce any new environment variables? If so, call them out explicitly here:**

### CODE REVIEW

**Comment by huumn** [comment]
> useWallets is a more appropriate location to check which image we should use.

Can you explain why that is the case? Isn't this mixing data and presentation and when we modify wallet cards, I now need to modify configuration loading?

Might it be better to just have a hook for this? e.g. `useWalletImage(wallet)`

**Comment by ekzyis** [comment]
> Can you explain why that is the case? Isn't this mixing data and presentation and when we modify wallet cards, I now need to modify configuration loading?

Mhh, I didn't see this as "mixing data and presentation", only as "returning the data the rest of the code needs". With doing the darkmode check in `useWallets`, other code doesn't need to be aware of this detail.

> Might it be better to just have a hook for this? e.g. `useWalletImage(wallet)`

Yeah this sounds better though and related to https://github.com/stackernews/stacker.news/pull/1643#discussion_r1855255109

**Comment by huumn** [comment]
> Mhh, I didn't see this as "mixing data and presentation", only as "returning the data the rest of the code needs". 

I had similar feelings about the way `status` was included in `useWallets`, but I didn't want to block that and knew we can easily refactor one violation out in the future. I definitely feel the urge myself to start doing this too though. I struggled with this a lot during my refactor.

**Comment by ekzyis** [comment]
> I had similar feelings about the way `status` was included in `useWallets`, but I didn't want to block that and knew we can easily refactor one violation out in the future. I definitely feel the urge myself to start doing this too though. I struggled with this a lot during my refactor.

lol, just created a PR for this: #1646

**Pull request merged**
