### PR TITLE
Dynamic protocol, host for share URLs so they work on localhost and in prod

### PR DESCRIPTION
**Pull request by SatsAllDay**
Basically the title... I wanted to use shared URLs in localhost and they were pointing to prod.

### CODE REVIEW

**Comment by ekzyis** [comment]
Why not use `process.env.PUBLIC_URL`?

**Comment by SatsAllDay** [comment]
> Why not use `process.env.PUBLIC_URL`?

Because that thought never occurred to me lol

Is it set to `https://stacker.news` in prod? If so, I can make this change.

**Comment by SatsAllDay** [comment]
Oh, looks like `PUBLIC_URL` only works server-side, we need to prefix it with `NEXT_PUBLIC` to get it to work client-side, so I think that's a blocker since I don't have the ability to configure new env vars for prod?

**Comment by ekzyis** [comment]
> Is it set to https://stacker.news in prod? If so, I can make this change.

Yes, but please confirm @huumn 

> Oh, looks like PUBLIC_URL only works server-side, we need to prefix it with NEXT_PUBLIC_

Ah yes, I think you can do that. I don't think that's a problem for anything.

> so I think that's a blocker since I don't have the ability to configure new env vars for prod?

I don't think that's a blocker. You don't need to configure new env vars. @huumn can set up env vars during deployment as he did for changes of mine in the past

**Comment by huumn** [comment]
> Yes, but please confirm @huumn

Confirmed

> You don't need to configure new env vars for prod. @huumn can set up env vars during deployment as he did for changes of mine in the past

I can but I also think using window.location is fine.

**Pull request merged**
