### PR TITLE
Add capture's container from /capture

### LINKED ISSUE #976: Add capture from /capture to sndev env
Pretty straightforward docker configuration stuff.

### PR DESCRIPTION
**Pull request by aniskhalfallah**
**Description**
Close #976

Straight forward docker-compose modification added the following to include capture from /capture: 
```  
  capture:
    container_name: capture
    build:
      context: ./capture
      args:
        - UID=${CURRENT_UID}
        - GID=${CURRENT_GID}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5678/health"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 1m
    env_file: .env.development
    expose:
      - "5678"
    ports:
      - "5678:5678"
    volumes:
      - ./:/app
    labels:
      CONNECT: "localhost:5678"
```

**Screenshots**

- [x] Are your changes backwards compatible?

- [x] Did you QA this? Could we deploy this straight to production?

- [ ] For frontend changes: Tested on mobile?

### CODE REVIEW

**Comment by huumn** [comment]
Welcome to the team! Please share a lightning address that I can send your sats to

**Comment by aniskhalfallah** [comment]
Thanks Keyan, Glad that I can be a part of the team ! @huumn here is my lightning address : aniskhalfallah@stacker.news
Is there a development team specific chat I can join?

**Comment by huumn** [comment]
We don't have a dev chat yet! I'll try to set one up soon

**Comment by aniskhalfallah** [comment]
Looking forward to that !

**Pull request merged**
